# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xdchs0RkBF3nbsLg8NYBMtZfeG4MO5g
"""

l=[int(x) for x in input("enter : ").split()]
l[2],l[4]=l[4],l[2]
l[3],l[4]=l[4],l[3]
print("gift_received_from list",l)

